### ISSUE TITLE
realtime_loop crahes

### ISSUE THREAD

**Issue by wyasuda** [start-jsk/open_industrial_ros_controllers#14]
```
[realtime_loop-4] process has died [pid 27820, exit code -11, cmd /home/wataru/catkin_ws_denso/devel/lib/denso_controller/main -x /opt/ros/hydro/share/vs060/model/vs060A1_AV6_NNN_NNN.urdf -s -d __name:=realtime_loop __log:=/home/wataru/.ros/log/6f49939a-63d5-11e3-bbd7-68a86d01cfae/realtime_loop-4.log].
log file: /home/wataru/.ros/log/6f49939a-63d5-11e3-bbd7-68a86d01cfae/realtime_loop-4*.log
```

gdb output is as follows

```
[New Thread 0xb2dffb40 (LWP 30247)]
[ WARN] [1386925513.364966168]: failed to read rt_period parameter
[ INFO] [1386925513.365190204]: realtime loop period is 1000000.000000

Program received signal SIGSEGV, Segmentation fault.
0xb7a15e29 in vfprintf () from /lib/i386-linux-gnu/libc.so.6
(gdb) where
#0  0xb7a15e29 in vfprintf () from /lib/i386-linux-gnu/libc.so.6
#1  0xb7ad4518 in __vsnprintf_chk () from /lib/i386-linux-gnu/libc.so.6
#2  0xb7df3a16 in ros::console::vformatToBuffer(boost::shared_array<char>&, unsigned int&, char const*, char*) () from /opt/ros/hydro/lib/librosconsole.so
#3  0xb7df426d in ros::console::print(ros::console::FilterBase*, log4cxx::Logger*, ros::console::levels::Level, char const*, int, char const*, char const*, ...) () from /opt/ros/hydro/lib/librosconsole.so
#4  0xb7db0719 in OpenControllersInterface::OpenController::initialize() ()
   from /home/wataru/catkin_ws_denso/devel/lib/libopen_controllers_interface.so
#5  0x0806c4c5 in main ()
```

**Comment by 130s** [comment]
+1

@garaemon ?

**Comment by garaemon** [comment]
merged, thanks!!

**Comment by k-okada** [comment]
I worked with @wyasuda , now he is business manager who can git push!
